### ISSUE TITLE
Please resolve dependence on envlogic library, which uses LGPL license

### ISSUE THREAD

**Issue by amilligan** [karafka/envlogic#50]
The most recent version of Karafka, while licensed under the MIT license, depends on (by default) version 1.1.2 of the envlogic gem, which is licensed under LGPL.  While not as restrictive as GPL, LGPL is a copyleft license that most corporate legal departments (including ours) will not accept.

We have been able to continue using Karafka by explicitly downgrading the version of envlogic to 1.1.1, which is licensed under MIT.  But, there's no guarantee that as karafka evolves that older version of the envlogic library will continue to work, so we now have a time bomb in our project.

We ask that you restore the envlogic license to MIT (it's not clear why that was changed in v1.1.2), dual license the envlogic gem with MIT (or, if you prefer, Apache 2.0, BSD, etc.), or remove/replace the envlogic library entirely.  As long as Karafka depends on a library using the LGPL the fact that Karafka itself uses the MIT license is not adequate to allow permissive use.

**Comment by mensfeld** [comment]
Hey @amilligan this got released prematurely and I forgot to revert it. Same with few others. This was supposed to be part of double licensing of this, sidekiq-backend, and the testing but not for 1.4. I think I merged it a while ago not where I wanted :confused:.

I will fix those this week and release proper versioning where it is needed. Sorry for the inconvenience :pray:

**Comment by mensfeld** [comment]
@amilligan I now resolved it in all the repositories. Sorry once again :pray:

**Comment by srp-developers** [comment]
@mensfeld We really appreciate the quick response on this.  Thanks for fixing this, and thanks for all your work maintaining this library.

**Comment by mensfeld** [comment]
@srp-developers anytime :) I'm well aware of how licensing issues can impact the development process (in a bad way).
